"""crear reports

Revision ID: 8ed03fddd180
Revises: a259af57dcfc
Create Date: 2026-08-10 19:33:49.208895

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ed03fddd180'
down_revision: Union[str, Sequence[str], None] = 'a259af57dcfc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reports',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('generated_at', sa.DateTime(), nullable=False),
    sa.Column('period', sa.String(), nullable=False),
    sa.Column('metrics_json', sa.String(), nullable=False),
    sa.Column('pdf_path', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reports')
    # ### end Alembic commands ###
