"""crear internal_metrics

Revision ID: a259af57dcfc
Revises: 
Create Date: 2026-08-10 18:53:32.591471

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a259af57dcfc'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


internal_metrics = sa.table(
    'internal_metrics',
    sa.column('name', sa.String),
    sa.column('value', sa.Float),
    sa.column('unit', sa.String),
)

SEED_METRICS = [
    {'name': 'monthly_revenue_usd', 'value': 128450.75, 'unit': 'USD'},
    {'name': 'active_orders', 'value': 342, 'unit': 'pedidos'},
    {'name': 'active_users', 'value': 1893, 'unit': 'usuarios'},
    {'name': 'churn_rate_pct', 'value': 3.2, 'unit': '%'},
]


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('internal_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###
    op.bulk_insert(internal_metrics, SEED_METRICS)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('internal_metrics')
    # ### end Alembic commands ###
